[workspace.package]
name = "poc5358"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "host",
    "guest/common",
    "guest/command",
]

[workspace.dependencies]
common = { path = "guest/common" }
host = { path = "host" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasmtime = "33.0"
wit-bindgen = "0.42"
