[workspace.package]
name = "poc5358"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "host",
    "wasm_command",
    "authorizer",
    "common",
]

[workspace.dependencies]
wasmtime = "33.0"
