[workspace.package]
name = "poc5358"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "host",
    "wasm_command",
    "authorizer",
    "common",
]

[workspace.dependencies]
common = { path = "common" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasmtime = "33.0"
wit-bindgen = "0.42"
