[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
wasmtime = { workspace = true }
