world authorizer {
    use types.{event-set, allow-set};

    export read-approval: func(signals: event-set, receptors: allow-set) -> bool;
    export write-approval: func(signals: event-set, receptors: allow-set) -> bool;
}
