package poc:wit;

world universe {
    use types.{read-set, view-set, write-set, event-set, allow-set};

    export read-request: func(args: string) -> read-set;
    export read-approval: func(signals: read-set, receptors: allow-set) -> bool;
    export write-request: func(view: view-set, args: string) -> write-set;
    export write-approval: func(signals: event-set, receptors: allow-set) -> bool;
}
